[package]
name = "sauce-nao"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "sauce-nao"
path = "src/main.rs"
required-features = [ "cli" ]

[dependencies]
itoa = "1.0.4"
reqwest = { version = "0.11.13", default-features = false, features = [ "json", "stream", "multipart" ] }
serde = { version = "1.0.152", features = [ "derive" ] }
serde_json = "1.0.89"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = [ "fs" ] }
tokio-util = { version = "0.7.4", features = ["codec"] }
url = { version = "2.3.1", features = [ "serde" ] }

# Optional
anyhow = { version = "1.0.68", optional = true }
argh = { version = "0.1.9", optional = true }
dirs-next = { version = "2.0.0", optional = true }
toml = { version = "0.5.10", optional = true }

[dev-dependencies]
tokio = { version = "1.23.0", features = [ "macros" ] }

[features]
default = [ "reqwest/default-tls" ]

native-tls = [ "reqwest/native-tls" ]
rustls-tls = [ "reqwest/rustls-tls" ]

cli = [ 
    "anyhow", 
    "argh",  
    "dirs-next",
    "tokio/rt-multi-thread",
    "toml",
]
